server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    #status-page-url: https://${eureka.instance.hostname}:${server.port}/info
    #health-check-url: https://${eureka.instance.hostname}:${server.port}/health
  client:
    #注册中心的职责就是维护服务实例,它并不需要去检索服务,设置为false
    fetch-registry: false
    #该应用为注册中心,设置为false,代表不向注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/