server:
  #Tomcat访问端口
  port: 8766
eureka:
  client:
    #客户端默认的访问路径
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    #配置feign去消费
    name: consumer-feign
#开启hystrix
feign:
  hystrix:
    enabled: true
## hystrix熔断触发默认超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000



