server:
  #Tomcat访问端口
  port: 8764
eureka:
  client:
    #客户端默认的访问路径
    service-url:
      defaultZone: http://localhost:8762/eureka/
#spring:
  #application:
    #配置resttemplate-ribbon去消费
   # name: resttemplate-ribbon
spring:
  application:
    #配置feign去消费
    name: consumer-feign
    #配置mysql数据源
  datasource:
    #用户名
    username: root
    #数据库密码
    password: sa@123
    #数据库驱动
    driver-class-name: com.mysql.jdbc.Driver
    #数据库路径
    url: jdbc:mysql://192.168.1.11:3306/xiaoshitou?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    validationQuery: SELECT 1 FROM DUAL
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    logSlowSql: true
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
#配置mybatis
mybatis:
  #配置mapper.xml的位置
  mapper-locations: classpath:Mybatis/mapperXml/*.xml
#配置druid
loginUsername: root
loginPassword: 123456
#http://localhost:8764/druid/sql.html  访问这个页面
